### ISSUE TITLE
Usage question 

### ISSUE THREAD

**Issue by nhsscience** [streamlinesocial/highcharts-regression#28]
Forgive the noob question --

How do I display R-squared for the fitted curve?

Using 2nd order polynominal over at:  http://mrgpg.co.uk/citizen/index_tmp.html

Cheers
Glen

**Comment by phpepe** [comment]
%r2 in the legend should work

**Comment by nhsscience** [comment]
Cheers - got that thanks

MMM... the value diplsayed is considerably difference from Excel -- (and shows as negative)

Excel -- calculates 0.654 and I get -0.71  (interesting the equation is the same between both - so I have faith that the regression is right - just not the R2)

The data file that is being used is here:  http://mrgpg.co.uk/citizen/data.csv

Any pointers?

Cheers
G

**Comment by Rashaine** [comment]
Just ran into the r2 issue too. The problem is that the regression methods sorts the result and the r2 calculation method accepts the unsorted data and the sorted results which of course no longer correspond. I'm going to create a bug for it, but for now i'm going to remove the sort in my local copy or sort the input data.

**Comment by phpepe** [comment]
Its solved on the new version
